logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# SpringAMQP配置 todo
spring:
  rabbitmq:
    host:  # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username:   # 用户名
    password:  # 密码